### ISSUE TITLE
OPA document for the sample application?

### ISSUE THREAD

**Issue by imercerwillow** [build-security/OPA-AspDotNetCore-Middleware#17]
Where is the policy document for the sample application? I realize it's not consumed directly by the example code, but could you maybe include it in the readme to help comprehension of the example?

**Comment by Ofir-Lapid** [comment]
Hi @imercerwillow,

We added a new readme file within the sample application project to clarify the usage of the OPA-AspDotNetCore-Middleware. The readme includes a step by step instructions as well as the Rego code that we use.

I hope it would be much easier now to integrate with it.

Thanks for your feedback !

Feel free to reach out,
Ofir
