### ISSUE TITLE
Possible collaboration

### ISSUE THREAD

**Issue by Ulimo** [build-security/OPA-AspDotNetCore-Middleware#19]
### Question

Hi, I am the author of https://github.com/koralium/OPADotNet and wondered how you would look at possible collaboration?
The focus of the package I posted is mostly on having an embedded OPA client, and enable resource based authorization.

Or is this package more leaned to be used together with build-security PDP (which might make the embedded mode not so important)?

**Comment by tehilabuildsecurity** [comment]
Hi @Ulimo , your OPADotNet repo looks very interesting, I would love to continue this discussion offline .
It would be great if you can please email me at tehila@build.security.
